pipeline:
  publish:
    image: plugins/docker
    tags: [ latest ]
    repo: drone/ca-certs
    secrets: [docker_username, docker_password]
    when:
      event:
        exclude:
        - pull_request
